packages:
- '.'
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: 64902eaa55b8fc5d1457c06d69ae41cbd11daaa5
  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: 083977ea24e223c339626f52054222a7497a279b
  extra-dep: true
- location:
     git: https://github.com/isomorphism/these.git
     commit: b3d74b7a5a68349489ad4079f85e79b6a5c34538
- location:
     git: https://github.com/ghcjs/ghcjs-base.git
     commit: dd7034ef8582ea8a175a71a988393a9d1ee86d6f
  extra-dep: true

extra-deps:
  - ref-tf-0.4.0.1
  - ghcjs-dom-0.2.4.0
  - zenc-0.1.1
  - dlist-0.7.1.2
  - webkitgtk3-javascriptcore-0.13.2.0
resolver: lts-7.4

# There is no nix support for GHCJS
nix:
    enable: false
